name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set environment variables from GitHub Secrets
        run: |
          echo "DB_URI=${{ secrets.DB_URI }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}" >> $GITHUB_ENV
          echo "RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}" >> $GITHUB_ENV
          echo "RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}" >> $GITHUB_ENV
          echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> $GITHUB_ENV
          echo "CONFIG_SERVER_URI=${{ secrets.CONFIG_SERVER_URI }}" >> $GITHUB_ENV
          echo "EUREKA_SERVER_URI=${{ secrets.EUREKA_SERVER_URI }}" >> $GITHUB_ENV
          echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> $GITHUB_ENV
          echo "KAFKA_HOST=${{ secrets.KAFKA_HOST }}" >> $GITHUB_ENV
          echo "KAFKA_PORT=${{ secrets.KAFKA_PORT }}" >> $GITHUB_ENV
          echo "KAFKA_TOPIC=${{ secrets.KAFKA_TOPIC }}" >> $GITHUB_ENV
          echo "KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }}" >> $GITHUB_ENV
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build